### ISSUE TITLE
  raise KeyError(key) from err KeyError: 'open' ERROR : could you specify requirement.txt? 

### ISSUE THREAD

**Issue by jakeyahn** [AaronKFC/iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures#2]
Traceback (most recent call last):
  File "/home/student/anaconda3/envs/irdpg/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_test.py", line 148, in <module>
    is_intraday=True, is_lack_margin=is_lack_margin, args=args)
  File "/home/student/Finrl/iRDPG/iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures/environment.py", line 137, in __init__
    self.Data=preProcessData(data_fn)  
  File "/home/student/Finrl/iRDPG/iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures/environment.py", line 51, in preProcessData
    df[newLabel] = df[cn]
  File "/home/student/anaconda3/envs/irdpg/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/student/anaconda3/envs/irdpg/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'open'

**Comment by jakeyahn** [comment]
solved! your 'IC_prophetic.csv' file is deprecated. there is no index!!!!!!

I changed data_fn = "data_preprocess/IF_tech_oriDT.csv" for demo_warmup.

**Comment by wangchong282** [comment]
你好，當我用自己的數據集進行訓練時總是會在運行中途報錯，比如我的一天的分鐘數是195個，它會報如下錯誤：Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexes\range.py", line 355, in get_loc
    return self._range.index(new_key)
ValueError: 195 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\jupyterFile\DQN2\self-iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures-main\main_train.py", line 127, in <module>
    rdpg.train(args.train_num_episodes, args.checkpoint, args.debug)
  File "D:\jupyterFile\DQN2\self-iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures-main\rdpg.py", line 169, in train
    action_bc, next_state, reward, done, infos = self.env.step(np.argmax(action))
  File "D:\jupyterFile\DQN2\self-iRDPG-for-Quantitative-Trading-on-Stock-Index-Futures-main\environment.py", line 230, in step
    action_bc = self.mktOb['phtAction'][self.stepIdx + (self.stateWinlen -1)]
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 882, in __getitem__
    return self._get_value(key)
  File "D:\Anaconda3\lib\site-packages\pandas\core\series.py", line 989, in _get_value
    loc = self.index.get_loc(label)
  File "D:\Anaconda3\lib\site-packages\pandas\core\indexes\range.py", line 357, in get_loc
    raise KeyError(key) from err
KeyError: 195
